[module]
path = "ecosystem::tui_markdown"

[dependencies]
"ecosystem::markdown" = "0.1.0"
"ecosystem::ansi" = "0.1.0"
"ecosystem::unicode_text" = "0.1.0"
"ecosystem::tui" = "0.1.0"
"ecosystem::terminal" = "0.1.0"
